### ISSUE TITLE
Wiki: Política de Branch

### ISSUE THREAD

**Issue by bernas1104** [EngSwCIC/monitoriaCIC#14]
Para o início do desenvolvimento do código da aplicação, é necessário criar uma polítca de branch para o repositório Github.

Essa será uma maneira - necessária - de organizar o desenvolvimento do projeto, tanto para a equipe, quanto para terceiros que venham a sugerir Pull Requests no futuro.

Essa issue depende de uma pesquisa sobre políticas de branch e qual será implementada para sua devida documentação.

**Comment by JomaSnow** [comment]
Tutorial de como usar GitFlow depois de instalado: https://jeffkreeftmeijer.com/git-flow/

Sugiro que todos leiam.
