### ISSUE TITLE
Pesquisa: Política de Branch

### ISSUE THREAD

**Issue by bernas1104** [EngSwCIC/monitoriaCIC#15]
É necessário uma pesquisa sobre políticas de branch para a escolha de uma a ser aplicada no projeto.

A motivação dessa política é a organização do repositório para o desenvolvimento da equipe e de terceiros que venham a submeter pull requests no futuro.

**Comment by JomaSnow** [comment]
Vincent Driessen’s branching model (GitFlow) parece nos atender muito bem, recomendo utilizar esta política de branching (é a política mais adotada nos repositórios apresentados como referência (https://github.com/fga-gpp-mds) pelo Rafael), considerando cada sprint como uma release, ficará bem organizado e auxiliará em manter um flow de trabalho constante.
https://jeffkreeftmeijer.com/git-flow/

https://datasift.github.io/gitflow/IntroducingGitFlow.html
