### ISSUE TITLE
Pesquisa: Gem 'Devise'

### ISSUE THREAD

**Issue by bernas1104** [EngSwCIC/monitoriaCIC#5]
## Estudar a Gem 'Devise'

Gem apresentada - apenas de nome - pelo monitor (Rafael) na reunião do dia (09/05).
É uma gem que serve para gerar ações de Login e Logout em uma aplicação Rails.
Como nenhum dos membros conhece a gem, é necessário um trabalho inicial de pesquisa e aprendizado para utilização no projeto.

**Comment by JomaSnow** [comment]
Dois vídeos bacanas que ensinam bem como começar a utilizar o devise:

https://www.youtube.com/watch?v=zJYuLebl-Js

https://www.youtube.com/watch?v=bpycGFWU2eU
